# Generated by Django 5.2.4 on 2025-11-15 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                ("id_direccion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_direccion", models.CharField(max_length=100)),
                ("state", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dirección",
                "verbose_name_plural": "Direcciones",
                "ordering": ["nombre_direccion"],
            },
        ),
        migrations.CreateModel(
            name="encargado_direccion",
            fields=[
                ("id_encargado", models.AutoField(primary_key=True, serialize=False)),
                (
                    "direccion",
                    models.OneToOneField(
                        db_column="id_direccion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encargado",
                        to="direcciones.direccion",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Encargado de Direccion",
                "verbose_name_plural": "Encargados de Direcciones",
                "ordering": ["usuario"],
            },
        ),
    ]
