# Generated by Django 5.2.4 on 2025-11-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('id_departamento', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id_respuestas', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencia',
                'db_table': 'tipo_incidencia',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_preguntas', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('id_encuesta', models.ForeignKey(db_column='ID_encuesta', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuesta.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
            },
        ),
    ]
