# Generated by Django 5.2.4 on 2025-11-15 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encuesta", "0001_initial"),
        ("incidencia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuestas",
            name="id_incidencia",
            field=models.ForeignKey(
                db_column="ID_incidencia",
                on_delete=django.db.models.deletion.CASCADE,
                to="incidencia.incidencia",
            ),
        ),
        migrations.AddField(
            model_name="respuestas",
            name="id_preguntas",
            field=models.ForeignKey(
                db_column="ID_preguntas",
                on_delete=django.db.models.deletion.CASCADE,
                to="encuesta.preguntas",
            ),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="id_tipo_incidencia",
            field=models.ForeignKey(
                db_column="ID_tipo_incidencia",
                on_delete=django.db.models.deletion.CASCADE,
                to="encuesta.tipoincidencia",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="respuestas",
            unique_together={("id_preguntas", "id_incidencia")},
        ),
    ]
