# Generated by Django 5.2.4 on 2025-11-15 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuadrillas", "0001_initial"),
        ("departamento", "0001_initial"),
        ("encuesta", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                ("id_incidencia", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                (
                    "direccion_incidente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lateral", models.CharField(blank=True, max_length=100, null=True)),
                ("longitud", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("derivada", "Derivada"),
                            ("rechazada", "Rechazada"),
                            ("proceso", "En Proceso"),
                            ("finalizada", "Finalizada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departamento.departamento",
                    ),
                ),
                (
                    "id_cuadrilla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cuadrillas.cuadrilla",
                    ),
                ),
                (
                    "id_encuesta",
                    models.ForeignKey(
                        db_column="ID_encuesta",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="encuesta.encuesta",
                    ),
                ),
                (
                    "id_territorial",
                    models.ForeignKey(
                        db_column="ID_territorial",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "incidencia",
            },
        ),
        migrations.CreateModel(
            name="DatosVecino",
            fields=[
                ("id_vicino", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion_vicina", models.CharField(max_length=255)),
                ("rat", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "id_encuesta",
                    models.ForeignKey(
                        db_column="ID_encuesta",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="encuesta.encuesta",
                    ),
                ),
                (
                    "id_incidencia",
                    models.ForeignKey(
                        db_column="ID_incidencia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidencia.incidencia",
                    ),
                ),
            ],
            options={
                "db_table": "datos_vecino",
            },
        ),
        migrations.CreateModel(
            name="ArchivosMultimedia",
            fields=[
                ("id_multimedia", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("documento", "Documento"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("archivo", models.FileField(upload_to="incidencias/multimedia/")),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "id_incidencia",
                    models.ForeignKey(
                        db_column="ID_incidencia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidencia.incidencia",
                    ),
                ),
            ],
            options={
                "db_table": "archivos_multimedia",
            },
        ),
        migrations.CreateModel(
            name="RegistrosRespuestas",
            fields=[
                ("id_reguerdas", models.AutoField(primary_key=True, serialize=False)),
                ("respuesta", models.TextField()),
                (
                    "id_incidencia",
                    models.ForeignKey(
                        db_column="ID_incidencia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidencia.incidencia",
                    ),
                ),
                (
                    "id_preguntas",
                    models.ForeignKey(
                        db_column="ID_preguntas",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="encuesta.preguntas",
                    ),
                ),
            ],
            options={
                "db_table": "registros_respuestas",
                "unique_together": {("id_preguntas", "id_incidencia")},
            },
        ),
    ]
