# Generated by Django 5.2.4 on 2025-11-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0001_initial'),
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='id_caudrilla',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='id_direuntamiento',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='id_cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadrillas.cuadrilla'),
        ),
    ]
