# Generated by Django 5.2.4 on 2025-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_remove_incidencia_id_caudrilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='direccion_incidente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
