# Generated by Django 5.2.4 on 2025-11-06 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id_cuadrilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuadrilla', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='departamento.departamento')),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
                'ordering': ['nombre_cuadrilla'],
            },
        ),
        migrations.CreateModel(
            name='Miembro_cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Operario', 'Operario'), ('Jefe de Cuadrilla', 'Jefe de Cuadrilla')], default='Operario', max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('cuadrilla', models.ForeignKey(db_column='id_cuadrilla', on_delete=django.db.models.deletion.CASCADE, to='cuadrillas.cuadrilla')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Cuadrilla',
                'verbose_name_plural': 'Miembros de las Cuadrillas',
                'ordering': ['cuadrilla__nombre_cuadrilla', 'usuario__first_name'],
                'unique_together': {('cuadrilla', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='jefe_cuadrilla',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'Jefe de Cuadrilla'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_dirigidas', to='cuadrillas.miembro_cuadrilla', unique=True),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='usuarios',
            field=models.ManyToManyField(related_name='cuadrillas', through='cuadrillas.Miembro_cuadrilla', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Registro_cierre',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cierre', models.DateField()),
                ('descripcion', models.TextField()),
                ('evidencia', models.FileField(upload_to='cuadrillas/')),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cuadrilla', models.ForeignKey(db_column='id_cuadrilla', on_delete=django.db.models.deletion.CASCADE, related_name='registros_cierre', to='cuadrillas.cuadrilla')),
            ],
            options={
                'verbose_name': 'Registro de Cierre',
                'verbose_name_plural': 'Registros de Cierre',
                'ordering': ['fecha_cierre'],
            },
        ),
    ]
