# Generated by Django 5.2.4 on 2025-11-15 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuadrillas", "0001_initial"),
        ("incidencia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro_cierre",
            name="incidencia",
            field=models.ForeignKey(
                blank=True,
                db_column="id_incidencia",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros_cierre",
                to="incidencia.incidencia",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="miembro_cuadrilla",
            unique_together={("cuadrilla", "usuario")},
        ),
    ]
