# Generated by Django 5.2.4 on 2025-11-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0001_initial'),
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_cierre',
            options={'ordering': ['-fecha_cierre'], 'verbose_name': 'Registro de Cierre', 'verbose_name_plural': 'Registros de Cierre'},
        ),
        migrations.AddField(
            model_name='registro_cierre',
            name='incidencia',
            field=models.ForeignKey(blank=True, db_column='id_incidencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_cierre', to='incidencia.incidencia'),
        ),
        migrations.AlterField(
            model_name='registro_cierre',
            name='cuadrilla',
            field=models.ForeignKey(db_column='id_cuadrilla', on_delete=django.db.models.deletion.CASCADE, related_name='registros_de_cierre', to='cuadrillas.cuadrilla'),
        ),
        migrations.AlterField(
            model_name='registro_cierre',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_cierre',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True),
        ),
    ]
