# Generated by Django 5.2.4 on 2025-11-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0003_alter_registro_cierre_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_cierre',
            name='comentario_territorial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_cierre',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True),
        ),
    ]
