# Generated by Django 5.2.4 on 2025-11-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0004_registro_cierre_comentario_territorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_cierre',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
